"""Standing rule: no result is generated by a script that is not committed first, and every manifest records the
script's git SHA.

    prov = run_provenance.script_provenance([__file__, other_module_files...], require_committed=True)
    manifest["script_provenance"] = prov

require_committed=True raises ProvenanceError if any listed file is untracked or has uncommitted changes. Use
require_committed=False only for scratch smoke runs whose output is not a result; the record then says
"committed": false so it can never be mistaken for a clean run.
"""

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


class ProvenanceError(Exception):
    pass


def _git(*args: str) -> str:
    r = subprocess.run(["git", "-C", str(REPO), *args], capture_output=True, text=True, timeout=60,
                       stdin=subprocess.DEVNULL)
    if r.returncode != 0:
        raise ProvenanceError(f"git {' '.join(args)} failed: {r.stderr.strip()}")
    return r.stdout.strip()


def script_provenance(paths, require_committed: bool = True) -> dict:
    head = _git("rev-parse", "HEAD")
    files = []
    problems = []
    for p in paths:
        p = Path(p).resolve()
        rel = p.relative_to(REPO).as_posix()
        tracked = subprocess.run(["git", "-C", str(REPO), "ls-files", "--error-unmatch", rel], capture_output=True,
                                 text=True, stdin=subprocess.DEVNULL).returncode == 0
        dirty = bool(_git("status", "--porcelain", "--", rel)) if tracked else True
        last = _git("log", "-1", "--format=%H", "--", rel) if tracked else None
        files.append({"path": rel, "tracked": tracked, "modified_or_untracked": dirty,
                      "last_commit_touching": last, "git_blob_sha": _git("hash-object", str(p)),
                      "sha256": hashlib.sha256(p.read_bytes()).hexdigest()})
        if not tracked:
            problems.append(f"{rel}: not tracked by git")
        elif dirty:
            problems.append(f"{rel}: has uncommitted changes")
    committed = not problems
    if require_committed and not committed:
        raise ProvenanceError("refusing to run, scripts not committed: " + "; ".join(problems))
    return {"git_head": head, "committed": committed, "problems": problems, "files": files}
