"""Standing rule: no result is generated by a script that is not committed first, and every manifest records the
script's git SHA.

    prov = run_provenance.script_provenance([__file__, other_module_files...], require_committed=True)
    manifest["script_provenance"] = prov

require_committed=True raises ProvenanceError if any listed file is untracked or has uncommitted changes. Use
require_committed=False only for scratch smoke runs whose output is not a result; the record then says
"committed": false so it can never be mistaken for a clean run.
"""

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


class ProvenanceError(Exception):
    pass


def _git(*args: str) -> str:
    r = subprocess.run(["git", "-C", str(REPO), *args], capture_output=True, text=True, timeout=60,
                       stdin=subprocess.DEVNULL)
    if r.returncode != 0:
        raise ProvenanceError(f"git {' '.join(args)} failed: {r.stderr.strip()}")
    return r.stdout.strip()


def _git_available():
    """False if the `git` executable is not on PATH at all, or REPO is not a git repository -- both are real on the
    machines this deploys to: C:\\apu\\ovn is a copy of committed files (via scripts/deploy_evo.py's `git show
    HEAD:<path>`), not a git clone, so neither git.exe nor a .git directory is guaranteed to exist there. Found
    2026-09-29 when t2s_k1_ollama.py crashed hard on evo-x2 with an uncaught FileNotFoundError before it ever
    reached its own try/finally (so the queue never advanced past it either)."""
    try:
        r = subprocess.run(["git", "-C", str(REPO), "rev-parse", "--is-inside-work-tree"], capture_output=True,
                           text=True, timeout=10, stdin=subprocess.DEVNULL)
        return r.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def script_provenance(paths, require_committed: bool = True) -> dict:
    """Raises ProvenanceError only when require_committed=True and either git itself is unavailable in this
    environment, or a listed file is untracked/uncommitted. When require_committed=False (the default for scratch/
    non-git-clone deploys), a missing git falls back to a degraded-but-non-crashing record ("committed": None,
    "git_head": None) instead of taking down the whole script before its own try/finally can run."""
    if not _git_available():
        msg = "git not available in this environment (no git.exe on PATH, or REPO is not a git repository)"
        if require_committed:
            raise ProvenanceError(msg)
        return {"git_head": None, "committed": None, "problems": [msg], "files": []}
    head = _git("rev-parse", "HEAD")
    files = []
    problems = []
    for p in paths:
        p = Path(p).resolve()
        rel = p.relative_to(REPO).as_posix()
        tracked = subprocess.run(["git", "-C", str(REPO), "ls-files", "--error-unmatch", rel], capture_output=True,
                                 text=True, stdin=subprocess.DEVNULL).returncode == 0
        dirty = bool(_git("status", "--porcelain", "--", rel)) if tracked else True
        last = _git("log", "-1", "--format=%H", "--", rel) if tracked else None
        files.append({"path": rel, "tracked": tracked, "modified_or_untracked": dirty,
                      "last_commit_touching": last, "git_blob_sha": _git("hash-object", str(p)),
                      "sha256": hashlib.sha256(p.read_bytes()).hexdigest()})
        if not tracked:
            problems.append(f"{rel}: not tracked by git")
        elif dirty:
            problems.append(f"{rel}: has uncommitted changes")
    committed = not problems
    if require_committed and not committed:
        raise ProvenanceError("refusing to run, scripts not committed: " + "; ".join(problems))
    return {"git_head": head, "committed": committed, "problems": problems, "files": files}


def git_blob_sha(data: bytes) -> str:
    """Same value as `git hash-object` for these bytes."""
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def verify_deployed_blobs(base_dir, expected_json_path) -> dict:
    """For machines without git (evo-t2s). expected_json_path holds {"git_head": sha, "blobs": {name: blob_sha}},
    written at deploy time from `git rev-parse HEAD:<path>` of the COMMITTED files, and the deployed bytes were
    produced with `git show HEAD:<path>`. Any mismatch raises ProvenanceError."""
    import json
    exp = json.loads(Path(expected_json_path).read_text(encoding="utf-8"))
    files, problems = [], []
    for name, want in exp["blobs"].items():
        data = (Path(base_dir) / name).read_bytes()
        got = git_blob_sha(data)
        files.append({"path": name, "expected_git_blob_sha": want, "actual_git_blob_sha": got,
                      "sha256": hashlib.sha256(data).hexdigest()})
        if got != want:
            problems.append(f"{name}: blob {got} != committed {want}")
    if problems:
        raise ProvenanceError("deployed scripts do not match the committed blobs: " + "; ".join(problems))
    return {"git_head": exp["git_head"], "committed": True, "verified_by": "git blob sha1 of deployed bytes",
            "problems": [], "files": files}
