"""Agent workload trace CDF: per-step context length from public agent trajectory datasets, tokenized with
real qwen3 and llama3.1 tokenizers.

IMPORTANT CENSORING CAVEAT (found after the first version of this script): nebius/SWE-agent-trajectories and
Kwai-Klear/SWE-smith-mini_swe_agent_plus-trajectories-66k are both CENSORED at their generating model's own
context limit. A trajectory cannot grow past whatever context the model that produced it could hold, so any
"nothing exceeds 32K" reading from those two alone is an artifact of the generator, not evidence about real
agent-step context demand. nebius/SWE-agent-trajectories was generated with Qwen2.5-72B-Instruct (32K native)
and Llama3-70B-Instruct (8K native); its own dataset card reports exit_status "Exit context" for 30.4% of
unresolved and 5.3% of resolved trajectories -- the generating model hit its own ceiling mid-task in roughly a
quarter of all runs, which is why nothing in that dataset is observed above ~29-32K. Kwai-Klear contains
successful trajectories only (a second, separate censoring: failure modes, including context exits, are absent
entirely). Both samples below take the first N rows of their stream, not a random sample.

This version adds:
  1. A direct measurement of nebius/SWE-agent-trajectories' exit_status field (context-exit rate), via a
     shuffled random sample (streaming shuffle buffer, fixed seed), split by resolved/unresolved and by
     model_name -- this is the evidence for the censoring claim above, not an assumption from the dataset card.
  2. Two UNCENSORED sources, generated by models with a native context far above what any step in them reaches,
     random-sampled the same way:
       (a) nebius/SWE-rebench-openhands-trajectories -- Qwen3-Coder-480B-A35B-Instruct (256K native),
           OpenHands v0.54.0 scaffolding. Field "trajectory": list of {role, content, tool_calls} dicts,
           role in {system, assistant, user, tool}.
       (b) SWE-Gym/OpenHands-Sampled-Trajectories -- gpt-4o-2024-08-06 / claude-3-5-sonnet-20241022 (128K /
           200K native), OpenHands scaffolding, split "train.raw". Field "messages": list of
           {role, content, tool_calls, name, tool_call_id} dicts. No per-row model field in the schema, so the
           two bootstrapping models cannot be told apart from the data; reported at the dataset level with
           both caps given.
     CAVEAT: OpenHands' agent controller has enable_history_truncation=True by default and will condense/chop
     history in half when a run hits the model's context window (github.com/OpenHands/OpenHands issues #6707,
     #7136, #8630, PR #7578; docs.openhands.dev/sdk/guides/context-condenser). Neither dataset card states
     whether condensation ever actually fired for these specific collection runs. If it did on some fraction of
     runs, the stored trajectory for those runs is post-condensation and a reconstructed cumulative prompt from
     it is a LOWER BOUND on what the runtime actually saw at the time, not the true uncensored growth. Reported
     as a caveat, not resolved, since no run-level condensation flag is exposed in either dataset's schema.

Usage: py -3.12 -u analysis/agent_traces.py
Outputs: results/traces/agent_step_lengths.parquet, results/traces/exit_status_sample.parquet,
         figures/fig_trace_cdf.png
"""
from __future__ import annotations

import json
import time
import traceback
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
N_TRAJECTORIES = 600
TIMEBOX_S = 300          # per-dataset step-CDF timebox (5 min), as in the first version
OPENHANDS_TIMEBOX_S = 600  # per the new instruction: 10 minutes each for the two uncensored sources
EXIT_STATUS_TIMEBOX_S = 300
EXIT_STATUS_N = 2000
SHUFFLE_BUFFER = 10000
SHUFFLE_SEED = 42

QWEN_MODEL = "Qwen/Qwen3-8B"
LLAMA_MODEL = "NousResearch/Meta-Llama-3.1-8B-Instruct"

THRESHOLDS = (8_000, 16_000, 32_000, 40_960, 64_000, 128_000)
TRAJ_THRESHOLDS = (32_000, 40_960, 64_000, 128_000)

# Native context ceiling of each dataset's generating model(s), for plot labeling and for the censoring
# argument. Where a dataset mixes models with no per-row field to split on, the dataset-level cap given is the
# lower of the two (the binding one for "nothing observed above X").
MODEL_CONTEXT_CAP = {
    # The dataset card's comparison table names Qwen2.5-72B-Instruct/Llama3-70B-Instruct as the bootstrapping
    # models, but the real model_name field (confirmed by direct sampling, not assumed) holds
    # swe-agent-llama-{405b,70b,8b} instead -- all Llama 3.1-family sizes, native context 128K each. The
    # observed exit_context ceiling clusters at ~29-32K regardless of which of these three ran, well below any
    # of their native 128K, so the binding constraint here is a SWE-agent scaffolding-imposed window, not the
    # model architecture's own ceiling. Caps below are the real per-model-name exit_context rates' implied
    # scaffolding cap (~32K observed), not the model's native context -- see the exit-status sample output for
    # the actual measured rate per model_name.
    "swe-agent-llama-405b": 32_768,
    "swe-agent-llama-70b": 32_768,
    "swe-agent-llama-8b": 32_768,
    "Qwen/Qwen3-Coder-480B-A35B-Instruct": 262_144,
}
KWAI_CAP_LABEL = "unknown (dataset card: unspecified)"
SWEGYM_CAP_LABEL = "gpt-4o-2024-08-06 (128K) / claude-3-5-sonnet-20241022 (200K), mixed, no per-row model field"

# K1 v3's measured (Ollama-chosen) default context per model, per host.
#
# evo-x2: CONFIRMED from a real, committed file -- results/t2s_k1_ollama_evo-x2_20260930T205515Z.jsonl (25 rows,
# K1 v3's own tier_v3_model_meta/tier rows, committed 2026-10-01). Ollama's own /api/ps ollama_default_ctx per
# model: qwen3-4b-2507 -> 262144 (matches its native ctx, uncapped), llama3.1:8b -> 131072 (matches its native
# ctx, uncapped), qwen3:8b -> 40960 (its own native ctx -- the "capped" control model, not memory-limited here).
# evo-x2 therefore did NOT pick a single memory-driven tier below any model's native ceiling in this run; every
# model landed at its own native ctx. A single "evo-x2 = 131072" blanket figure (used in an earlier version of
# this file, A7 2026-09-30 flagged it as an unconfirmed carry-over) was wrong in a specific, now-fixable way: it
# silently assumed one tier applies to every model, when the real per-model data shows otherwise.
#
# evo-t2s: NOT YET CONFIRMED. No results/t2s_k1_ollama_evo-t2s_*.jsonl exists in this repo as of 2026-10-01 --
# its first post-A1/A2-fix attempt measured zero models (all three failed to become available; see commit
# 655a92a), and a retry is queued first in evo-t2s's pending queue. K1_T2S_EFFECTIVE_CTX stays None per model
# until that real file exists; truncation_cliff_table() below must not silently substitute a guess for it.
K1_X2_EFFECTIVE_CTX = {"qwen3-4b-2507": 262_144, "llama3.1:8b": 131_072, "qwen3:8b": 40_960}
K1_X2_EFFECTIVE_CTX_SOURCE = "results/t2s_k1_ollama_evo-x2_20260930T205515Z.jsonl (committed, real)"
K1_T2S_EFFECTIVE_CTX = None  # no real file yet -- see comment above
K1_V3_MODEL_NATIVE_CTX = {"qwen3-4b-2507": 262_144, "llama3.1:8b": 131_072, "qwen3:8b": 40_960}


def load_tokenizers():
    from transformers import AutoTokenizer
    tok_qwen = AutoTokenizer.from_pretrained(QWEN_MODEL)
    tok_llama = AutoTokenizer.from_pretrained(LLAMA_MODEL)
    return tok_qwen, tok_llama


def count_tokens(tok, text):
    if not text:
        return 0
    return len(tok(text, add_special_tokens=False)["input_ids"])


def _tool_calls_text(tool_calls):
    """Serializes an assistant message's tool_calls to text so they count toward the prompt the runtime would
    actually have to encode (tool-call tokens are real prompt tokens, not free)."""
    if not tool_calls:
        return ""
    try:
        return json.dumps(tool_calls, ensure_ascii=False)
    except Exception:
        return str(tool_calls)


def iter_nebius_steps(row):
    """Yields (step_idx, system_text, cumulative_text) for each assistant ("ai") turn in a nebius SWE-agent
    trajectory."""
    traj = row.get("trajectory") or []
    system_text = ""
    history_parts = []
    step_idx = 0
    for m in traj:
        role = m.get("role")
        text = m.get("system_prompt") if role == "system" else m.get("text")
        text = text or ""
        if role == "system":
            system_text = text
            history_parts.append(text)
            continue
        history_parts.append(text)
        if role == "ai":
            step_idx += 1
            cumulative = "\n".join(history_parts)
            yield step_idx, system_text, cumulative


def iter_swesmith_steps(row):
    """Yields (step_idx, system_text, cumulative_text) for each assistant turn in a Kwai-Klear SWE-smith
    trajectory."""
    msgs = row.get("messages") or []
    system_text = ""
    history_parts = []
    step_idx = 0
    for m in msgs:
        role = m.get("role")
        content = m.get("content") or ""
        if role == "system":
            system_text = content
            history_parts.append(content)
            continue
        history_parts.append(content)
        if role == "assistant":
            step_idx += 1
            cumulative = "\n".join(history_parts)
            yield step_idx, system_text, cumulative


def iter_openhands_steps(row):
    """Yields (step_idx, system_text, cumulative_text) for each assistant turn in an OpenHands-scaffolded
    trajectory (both nebius/SWE-rebench-openhands-trajectories' "trajectory" field and
    SWE-Gym/OpenHands-Sampled-Trajectories' "messages" field share this role/content/tool_calls shape).
    Tool-call arguments and tool-result content both count toward cumulative prompt size."""
    msgs = row.get("trajectory") if row.get("trajectory") is not None else row.get("messages")
    msgs = msgs or []
    system_text = ""
    history_parts = []
    step_idx = 0
    for m in msgs:
        role = m.get("role")
        content = m.get("content") or ""
        tool_text = _tool_calls_text(m.get("tool_calls"))
        piece = (content + "\n" + tool_text) if tool_text else content
        if role == "system":
            system_text = content
            history_parts.append(piece)
            continue
        history_parts.append(piece)
        if role == "assistant":
            step_idx += 1
            cumulative = "\n".join(history_parts)
            yield step_idx, system_text, cumulative


DATASETS = {
    # traj_id_fn: none of these datasets' "instance_id" is a unique per-trajectory key -- every one of them
    # collects multiple runs/attempts per GitHub issue (different models, or repeated samples of the same
    # instance), so instance_id alone collides across trajectories. Found live: a first version of this script
    # used instance_id and it silently merged 133 real nebius trajectories down to 10 "trajectories". Fixed by
    # using each dataset's real unique per-run field where the schema provides one (trajectory_id for the
    # nebius OpenHands set, run_id for SWE-Gym), and instance_id + the stream enumeration index elsewhere.
    "nebius/SWE-agent-trajectories": {
        "iter_fn": iter_nebius_steps, "split": "train", "resolved_field": "target",
        "cap_fn": lambda row: MODEL_CONTEXT_CAP.get(row.get("model_name"), None),
        "model_field": "model_name",
        "traj_id_fn": lambda row, i: f"{row.get('instance_id')}::{i}",
    },
    "Kwai-Klear/SWE-smith-mini_swe_agent_plus-trajectories-66k": {
        "iter_fn": iter_swesmith_steps, "split": "train", "resolved_field": None,
        "cap_fn": lambda row: None, "model_field": None,
        "traj_id_fn": lambda row, i: f"{row.get('instance_id')}::{i}",
    },
    "nebius/SWE-rebench-openhands-trajectories": {
        "iter_fn": iter_openhands_steps, "split": "train", "resolved_field": "resolved",
        "cap_fn": lambda row: MODEL_CONTEXT_CAP["Qwen/Qwen3-Coder-480B-A35B-Instruct"], "model_field": None,
        "timebox_s": OPENHANDS_TIMEBOX_S,
        "traj_id_fn": lambda row, i: row.get("trajectory_id") or f"{row.get('instance_id')}::{i}",
    },
    "SWE-Gym/OpenHands-Sampled-Trajectories": {
        "iter_fn": iter_openhands_steps, "split": "train.raw", "resolved_field": "resolved",
        "cap_fn": lambda row: None, "model_field": None,
        "timebox_s": OPENHANDS_TIMEBOX_S,
        # run_id turned out NOT unique per trajectory either (found live: it collapsed 600 real trajectories to
        # 3 -- it looks like a sampling-attempt index shared across many different issues, not a per-row id).
        # Always suffix with the stream enumeration index so uniqueness is guaranteed within our own sample,
        # regardless of what any dataset's own id field actually means.
        "traj_id_fn": lambda row, i: f"{row.get('instance_id')}::{row.get('run_id')}::{i}",
    },
}


def process_dataset(name, spec, tok_qwen, tok_llama, n_trajectories=N_TRAJECTORIES):
    from datasets import load_dataset

    step_iter_fn = spec["iter_fn"]
    timebox_s = spec.get("timebox_s", TIMEBOX_S)
    resolved_field = spec.get("resolved_field")
    rows = []
    t0 = time.monotonic()
    try:
        ds = load_dataset(name, split=spec["split"], streaming=True)
        print(f"{name}: columns = {ds.features and list(ds.features.keys())}", flush=True)
        print(f"{name}: starting stream (timebox {timebox_s}s)", flush=True)
        it = iter(ds)
        n_traj_done = 0
        for traj_idx in range(n_trajectories):
            if time.monotonic() - t0 > timebox_s:
                print(f"{name}: timeboxed at {timebox_s}s, stopping with {n_traj_done} trajectories done", flush=True)
                break
            fetch_t0 = time.monotonic()
            try:
                row = next(it)
            except StopIteration:
                print(f"{name}: dataset exhausted at {n_traj_done} trajectories", flush=True)
                break
            fetch_dt = time.monotonic() - fetch_t0
            resolved = row.get(resolved_field) if resolved_field else None
            if resolved is not None:
                resolved = bool(resolved)
            cap = spec["cap_fn"](row)
            traj_id = spec["traj_id_fn"](row, traj_idx)
            n_steps_this_traj = 0
            steps_buffer = []
            for step_idx, system_text, cumulative in step_iter_fn(row):
                tq = count_tokens(tok_qwen, cumulative)
                tl = count_tokens(tok_llama, cumulative)
                sq = count_tokens(tok_qwen, system_text)
                sl = count_tokens(tok_llama, system_text)
                steps_buffer.append({
                    "dataset": name, "trajectory_id": traj_id,
                    "step_idx": step_idx, "tokens_qwen": tq, "tokens_llama": tl,
                    "system_tokens_qwen": sq, "system_tokens_llama": sl,
                    "resolved": resolved, "generator_context_cap": cap,
                })
                n_steps_this_traj += 1
            for r in steps_buffer:
                r["n_steps_total"] = n_steps_this_traj
            rows.extend(steps_buffer)
            n_traj_done += 1
            if n_traj_done % 25 == 0 or fetch_dt > 5.0:
                print(f"{name}: {n_traj_done}/{n_trajectories} trajectories, {len(rows)} steps so far, "
                     f"{time.monotonic() - t0:.1f}s elapsed, last fetch {fetch_dt:.1f}s", flush=True)
    except Exception as e:
        print(f"{name}: ERROR after {time.monotonic() - t0:.1f}s, {len(rows)} rows collected so far:")
        traceback.print_exc()
        return rows, repr(e)
    print(f"{name}: {n_traj_done} trajectories, {len(rows)} steps, {time.monotonic() - t0:.1f}s")
    return rows, None


def sample_exit_status(name="nebius/SWE-agent-trajectories", n=EXIT_STATUS_N, timebox_s=EXIT_STATUS_TIMEBOX_S):
    """Random sample (streaming shuffle buffer, fixed seed) of exit_status, target, model_name -- the direct
    evidence for the censoring claim, not an assumption from the dataset card's aggregated table."""
    from datasets import load_dataset

    t0 = time.monotonic()
    rows = []
    try:
        ds = load_dataset(name, split="train", streaming=True)
        ds = ds.shuffle(buffer_size=SHUFFLE_BUFFER, seed=SHUFFLE_SEED)
        it = iter(ds)
        print(f"exit_status sample: shuffling {name} (buffer={SHUFFLE_BUFFER}, seed={SHUFFLE_SEED}, "
              f"target n={n}, timebox {timebox_s}s)", flush=True)
        for i in range(n):
            if time.monotonic() - t0 > timebox_s:
                print(f"exit_status sample: timeboxed at {timebox_s}s, stopping with {len(rows)} rows", flush=True)
                break
            try:
                row = next(it)
            except StopIteration:
                print(f"exit_status sample: dataset exhausted at {len(rows)} rows", flush=True)
                break
            rows.append({
                "exit_status": row.get("exit_status"), "target": bool(row.get("target")),
                "model_name": row.get("model_name"),
            })
            if (i + 1) % 250 == 0:
                print(f"exit_status sample: {i + 1}/{n} rows, {time.monotonic() - t0:.1f}s", flush=True)
    except Exception as e:
        print(f"exit_status sample: ERROR after {time.monotonic() - t0:.1f}s, {len(rows)} rows collected:")
        traceback.print_exc()
        return rows, repr(e)
    print(f"exit_status sample: {len(rows)} rows, {time.monotonic() - t0:.1f}s", flush=True)
    return rows, None


def summarize_exit_status(rows):
    import pandas as pd
    df = pd.DataFrame(rows)
    if df.empty:
        return df, {}
    distinct = sorted(df["exit_status"].dropna().unique().tolist())
    df["is_context_exit"] = df["exit_status"].astype(str).str.contains("context", case=False, na=False)
    out = {
        "n": len(df), "distinct_exit_status_values": distinct,
        "overall_context_exit_rate": float(df["is_context_exit"].mean()),
    }
    by_resolved = df.groupby("target")["is_context_exit"].mean().to_dict()
    out["context_exit_rate_by_resolved"] = {("resolved" if k else "unresolved"): float(v) for k, v in by_resolved.items()}
    by_model = df.groupby("model_name")["is_context_exit"].agg(["mean", "count"]).to_dict("index")
    out["context_exit_rate_by_model"] = {k: {"rate": float(v["mean"]), "n": int(v["count"])} for k, v in by_model.items()}
    return df, out


def build_parquet(all_rows, out_path):
    import pandas as pd
    df = pd.DataFrame(all_rows)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(out_path, index=False)
    return df


def build_cdf_plot(df, out_path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np

    cap_label = {
        "nebius/SWE-agent-trajectories": "Qwen2.5-72B/Llama3-70B, 8K-32K native (CENSORED)",
        "Kwai-Klear/SWE-smith-mini_swe_agent_plus-trajectories-66k": f"generator {KWAI_CAP_LABEL} (CENSORED, resolved-only)",
        "nebius/SWE-rebench-openhands-trajectories": "Qwen3-Coder-480B, 256K native",
        "SWE-Gym/OpenHands-Sampled-Trajectories": SWEGYM_CAP_LABEL,
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(9, 6))
    for name, group in df.groupby("dataset"):
        vals = np.sort(group["tokens_qwen"].to_numpy())
        if len(vals) == 0:
            continue
        cdf = np.arange(1, len(vals) + 1) / len(vals)
        label = f"{name}\n  [{cap_label.get(name, '')}]"
        ax.plot(vals, cdf, label=label)
    ax.set_xscale("log")
    ax.set_xlabel("step context length (tokens, qwen3 tokenizer)")
    ax.set_ylabel("CDF")
    ax.set_title("Agent-step context length, real trajectories\n(two datasets censored at the generating model's own context limit)")
    ax.legend(fontsize=6.5, loc="lower right")
    for t in THRESHOLDS:
        ax.axvline(t, color="gray", linestyle=":", linewidth=0.7)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def summarize(df):
    import numpy as np
    out = {}
    for name, group in df.groupby("dataset"):
        out[name] = {}
        splits = [("all", group)]
        if group["resolved"].notna().any():
            splits.append(("resolved", group[group["resolved"] == True]))
            splits.append(("unresolved", group[group["resolved"] == False]))
        for split_name, g in splits:
            if len(g) == 0:
                continue
            n_traj = g["trajectory_id"].nunique()
            vals_q = g["tokens_qwen"].to_numpy()
            frac_over = {t: float((vals_q > t).mean()) for t in THRESHOLDS}
            traj_max = g.groupby("trajectory_id")["tokens_qwen"].max()
            frac_traj_over = {t: float((traj_max > t).mean()) for t in TRAJ_THRESHOLDS}
            out[name][split_name] = {
                "n_trajectories": int(n_traj), "n_steps": int(len(g)),
                "qwen_p50": float(np.percentile(vals_q, 50)), "qwen_p90": float(np.percentile(vals_q, 90)),
                "qwen_p99": float(np.percentile(vals_q, 99)),
                "frac_steps_over_threshold": frac_over,
                "frac_trajectories_ever_over": frac_traj_over,
            }
    return out


def truncation_cliff_table(df):
    """Key number for the paper: of steps in the UNCENSORED dataset(s), what fraction exceed each host's real,
    per-model measured K1 v3 effective context. evo-x2 uses K1_X2_EFFECTIVE_CTX (confirmed from a real
    committed file, per model -- see its comment). evo-t2s is skipped entirely (not computed, not guessed)
    until a real results/t2s_k1_ollama_evo-t2s_*.jsonl exists; the returned dict's "evo-t2s" entry states this
    rather than silently omitting the host, so a caller printing this table sees why T2S is missing instead of
    assuming it was forgotten."""
    uncensored = df[df["dataset"].isin([
        "nebius/SWE-rebench-openhands-trajectories", "SWE-Gym/OpenHands-Sampled-Trajectories",
    ])]
    out = {"evo-t2s": {"status": "blocked: no real completed K1 v3 tier-sweep file exists yet for evo-t2s "
                                 "(see K1_T2S_EFFECTIVE_CTX's comment); not computed from a guess"}}
    out["evo-x2"] = {"source": K1_X2_EFFECTIVE_CTX_SOURCE, "per_model": {}}
    for model, ctx in K1_X2_EFFECTIVE_CTX.items():
        native = K1_V3_MODEL_NATIVE_CTX.get(model, ctx)
        binding_ctx = min(ctx, native)
        for name, group in uncensored.groupby("dataset"):
            vals = group["tokens_qwen"].to_numpy()
            if len(vals) == 0:
                continue
            frac = float((vals > binding_ctx).mean())
            out["evo-x2"]["per_model"].setdefault(model, {})[name] = {
                "binding_ctx": binding_ctx, "frac_steps_over": frac,
            }
    return out


def main():
    tok_qwen, tok_llama = load_tokenizers()

    exit_rows, exit_err = sample_exit_status()
    exit_df, exit_summary = summarize_exit_status(exit_rows)
    if not exit_df.empty:
        exit_df.to_parquet(ROOT / "results" / "traces" / "exit_status_sample.parquet", index=False)
    print("\n=== EXIT STATUS SAMPLE (nebius/SWE-agent-trajectories) ===")
    print(json.dumps(exit_summary, indent=2))
    if exit_err:
        print(f"exit_status sample error: {exit_err}")

    all_rows = []
    errors = {}
    for name, spec in DATASETS.items():
        rows, err = process_dataset(name, spec, tok_qwen, tok_llama)
        all_rows.extend(rows)
        if err:
            errors[name] = err

    if not all_rows:
        print("no rows collected from any dataset, nothing to write")
        return

    df = build_parquet(all_rows, ROOT / "results" / "traces" / "agent_step_lengths.parquet")
    build_cdf_plot(df, ROOT / "figures" / "fig_trace_cdf.png")
    summary = summarize(df)

    print("\n=== SUMMARY (per dataset, per resolved/unresolved split) ===")
    print(json.dumps(summary, indent=2))

    print("\n=== TRUNCATION CLIFF (uncensored datasets vs K1 v3 measured effective context) ===")
    cliff = truncation_cliff_table(df)
    print(json.dumps(cliff, indent=2))

    if errors:
        print("\n=== ERRORS ===")
        for name, e in errors.items():
            print(f"{name}: {e}")


if __name__ == "__main__":
    main()
